# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/RandomForest_for_smart_home_data

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/RandomForest_for_smart_home_data

# Include any dependencies generated for this target.
include src/CMakeFiles/../rf_exe.dir/depend.make

# Include the progress variables for this target.
include src/CMakeFiles/../rf_exe.dir/progress.make

# Include the compile flags for this target's objects.
include src/CMakeFiles/../rf_exe.dir/flags.make

src/CMakeFiles/../rf_exe.dir/main_training.cpp.o: src/CMakeFiles/../rf_exe.dir/flags.make
src/CMakeFiles/../rf_exe.dir/main_training.cpp.o: src/main_training.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/RandomForest_for_smart_home_data/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object src/CMakeFiles/../rf_exe.dir/main_training.cpp.o"
	cd /home/pi/RandomForest_for_smart_home_data/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../rf_exe.dir/main_training.cpp.o -c /home/pi/RandomForest_for_smart_home_data/src/main_training.cpp

src/CMakeFiles/../rf_exe.dir/main_training.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../rf_exe.dir/main_training.cpp.i"
	cd /home/pi/RandomForest_for_smart_home_data/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/RandomForest_for_smart_home_data/src/main_training.cpp > CMakeFiles/../rf_exe.dir/main_training.cpp.i

src/CMakeFiles/../rf_exe.dir/main_training.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../rf_exe.dir/main_training.cpp.s"
	cd /home/pi/RandomForest_for_smart_home_data/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/RandomForest_for_smart_home_data/src/main_training.cpp -o CMakeFiles/../rf_exe.dir/main_training.cpp.s

src/CMakeFiles/../rf_exe.dir/main_training.cpp.o.requires:

.PHONY : src/CMakeFiles/../rf_exe.dir/main_training.cpp.o.requires

src/CMakeFiles/../rf_exe.dir/main_training.cpp.o.provides: src/CMakeFiles/../rf_exe.dir/main_training.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../rf_exe.dir/build.make src/CMakeFiles/../rf_exe.dir/main_training.cpp.o.provides.build
.PHONY : src/CMakeFiles/../rf_exe.dir/main_training.cpp.o.provides

src/CMakeFiles/../rf_exe.dir/main_training.cpp.o.provides.build: src/CMakeFiles/../rf_exe.dir/main_training.cpp.o


src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o: src/CMakeFiles/../rf_exe.dir/flags.make
src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o: src/rts_forest.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/RandomForest_for_smart_home_data/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o"
	cd /home/pi/RandomForest_for_smart_home_data/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../rf_exe.dir/rts_forest.cpp.o -c /home/pi/RandomForest_for_smart_home_data/src/rts_forest.cpp

src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../rf_exe.dir/rts_forest.cpp.i"
	cd /home/pi/RandomForest_for_smart_home_data/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/RandomForest_for_smart_home_data/src/rts_forest.cpp > CMakeFiles/../rf_exe.dir/rts_forest.cpp.i

src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../rf_exe.dir/rts_forest.cpp.s"
	cd /home/pi/RandomForest_for_smart_home_data/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/RandomForest_for_smart_home_data/src/rts_forest.cpp -o CMakeFiles/../rf_exe.dir/rts_forest.cpp.s

src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o.requires:

.PHONY : src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o.requires

src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o.provides: src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../rf_exe.dir/build.make src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o.provides.build
.PHONY : src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o.provides

src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o.provides.build: src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o


src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o: src/CMakeFiles/../rf_exe.dir/flags.make
src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o: src/rts_tree.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/pi/RandomForest_for_smart_home_data/CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o"
	cd /home/pi/RandomForest_for_smart_home_data/src && /usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../rf_exe.dir/rts_tree.cpp.o -c /home/pi/RandomForest_for_smart_home_data/src/rts_tree.cpp

src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../rf_exe.dir/rts_tree.cpp.i"
	cd /home/pi/RandomForest_for_smart_home_data/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/pi/RandomForest_for_smart_home_data/src/rts_tree.cpp > CMakeFiles/../rf_exe.dir/rts_tree.cpp.i

src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../rf_exe.dir/rts_tree.cpp.s"
	cd /home/pi/RandomForest_for_smart_home_data/src && /usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/pi/RandomForest_for_smart_home_data/src/rts_tree.cpp -o CMakeFiles/../rf_exe.dir/rts_tree.cpp.s

src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o.requires:

.PHONY : src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o.requires

src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o.provides: src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o.requires
	$(MAKE) -f src/CMakeFiles/../rf_exe.dir/build.make src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o.provides.build
.PHONY : src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o.provides

src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o.provides.build: src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o


# Object files for target ../rf_exe
__/rf_exe_OBJECTS = \
"CMakeFiles/../rf_exe.dir/main_training.cpp.o" \
"CMakeFiles/../rf_exe.dir/rts_forest.cpp.o" \
"CMakeFiles/../rf_exe.dir/rts_tree.cpp.o"

# External object files for target ../rf_exe
__/rf_exe_EXTERNAL_OBJECTS =

src/../rf_exe: src/CMakeFiles/../rf_exe.dir/main_training.cpp.o
src/../rf_exe: src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o
src/../rf_exe: src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o
src/../rf_exe: src/CMakeFiles/../rf_exe.dir/build.make
src/../rf_exe: src/CMakeFiles/../rf_exe.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/pi/RandomForest_for_smart_home_data/CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Linking CXX executable ../rf_exe"
	cd /home/pi/RandomForest_for_smart_home_data/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../rf_exe.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/CMakeFiles/../rf_exe.dir/build: src/../rf_exe

.PHONY : src/CMakeFiles/../rf_exe.dir/build

src/CMakeFiles/../rf_exe.dir/requires: src/CMakeFiles/../rf_exe.dir/main_training.cpp.o.requires
src/CMakeFiles/../rf_exe.dir/requires: src/CMakeFiles/../rf_exe.dir/rts_forest.cpp.o.requires
src/CMakeFiles/../rf_exe.dir/requires: src/CMakeFiles/../rf_exe.dir/rts_tree.cpp.o.requires

.PHONY : src/CMakeFiles/../rf_exe.dir/requires

src/CMakeFiles/../rf_exe.dir/clean:
	cd /home/pi/RandomForest_for_smart_home_data/src && $(CMAKE_COMMAND) -P CMakeFiles/../rf_exe.dir/cmake_clean.cmake
.PHONY : src/CMakeFiles/../rf_exe.dir/clean

src/CMakeFiles/../rf_exe.dir/depend:
	cd /home/pi/RandomForest_for_smart_home_data && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/pi/RandomForest_for_smart_home_data /home/pi/RandomForest_for_smart_home_data/src /home/pi/RandomForest_for_smart_home_data /home/pi/RandomForest_for_smart_home_data/src /home/pi/RandomForest_for_smart_home_data/src/rf_exe.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/CMakeFiles/../rf_exe.dir/depend

