# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# compile CXX with /usr/bin/c++
CXX_FLAGS =  -std=c++11 -Wall -Wextra -pedantic  

CXX_DEFINES = 

CXX_INCLUDES = -I/home/pi/RandomForest_for_smart_home_data/include 

